connector.name=postgresql
connection-url=jdbc:postgresql://postgres:5432/unimed
connection-user=unimed
connection-password=unimed
case-insensitive-name-matching=true
postgresql.array-mapping=AS_ARRAY
